const addresses = [
  {
    _id: "659fd2b8f53944a2c36fa8f7",
    userId: "6578cde3d24209970e67ae7f",
    addressLine1: "600 Stockton St, San Francisco, CA 94108, USA",
    postalCode: "94108",
    default: true,
    deliveryInstructions: "put the order by the gate",
    latitude: 37.79155946963518,
    longitude: -122.40726202726366,
    __v: 0,
  },

  {
    _id: "659fd2b8f537987a2c36fa8f7",
    userId: "6578cde3d24209970e67ae7f",
    addressLine1: "600 Stockton St, San Francisco, CA 94108, USA",
    postalCode: "94108",
    default: true,
    deliveryInstructions: "put the order by the gate",
    latitude: 37.79155946963518,
    longitude: -122.40726202726366,
    __v: 0,
  },

  {
    _id: "6578cde3d24209970e67ae7f",
    userId: "6578cde3d24209970e67ae7f",
    addressLine1: "600 Stockton St, San Francisco, CA 94108, USA",
    postalCode: "94108",
    default: true,
    deliveryInstructions: "put the order by the gate",
    latitude: 37.79155946963518,
    longitude: -122.40726202726366,
    __v: 0,
  },
];

const background =
  "https://d326fntlu7tb1e.cloudfront.net/uploads/ff869e45-561e-47f8-b4e6-40ef5d229c00-8cd2cb78-c99c-4408-a333-91ec6c1bb9e3-restaurant_bk.webp";

const foodTags = [
  "Abacha",
  "Afang Soup",
  "Amala",
  "Banga Soup",
  "Beans",
  "BBQ Chicken Pizza",
  "BBQ Wings",
  "Beef Burger",
  "Beef Shawarma",
  "Beer",
  "Burgers",
  "Caesar Salad",
  "Cheese Pizza",
  "Cheeseburgers",
  "Chicken Burger",
  "Chicken Salad",
  "Chicken Shawarma",
  "Chicken Wings",
  "Chin Chin",
  "Club Sandwich",
  "Cocktails",
  "Coffee",
  "Corn Dogs",
  "Cookies",
  "Cupcakes",
  "Dairy-Free",
  "Diabetic-Friendly",
  "Donuts",
  "Eba",
  "Edikang Ikong",
  "Egg-Free",
  "Egusi Soup",
  "Ewedu",
  "Festive",
  "Finger Foods",
  "French Fries",
  "Fried Chicken",
  "Fried Rice",
  "Fufu",
  "Goat Meat",
  "Gluten-Free",
  "Grilled Chicken",
  "Grilled Fish",
  "Halal",
  "Healthy Options",
  "Heart-Healthy",
  "High-Fiber",
  "High-Protein",
  "Hot Chocolate",
  "Hot Dogs",
  "Ice Cream",
  "Indomie",
  "Isi Ewu",
  "Jollof Rice",
  "Juices",
  "Kebabs",
  "Keto",
  "Kosher",
  "Kunu",
  "Loaded Fries",
  "Local Cuisine",
  "Low-Carb",
  "Low-Fat",
  "Low-Sodium",
  "Mac and Cheese",
  "Meat Lover's Pizza",
  "Milkshakes",
  "Mocktails",
  "Moi Moi",
  "Native Rice",
  "Non-GMO",
  "Nkwobi",
  "Noodles",
  "Nut-Free",
  "Ofada Rice",
  "Ogbono Soup",
  "Okro Soup",
  "Organic",
  "Palm Oil-Free",
  "Panini",
  "Party Food",
  "Pasta",
  "Pepperoni Pizza",
  "Peppered Chicken",
  "Peppered Fish",
  "Pescatarian",
  "Pizza",
  "Plantain",
  "Popcorn",
  "Pounded Yam",
  "Puff Puff",
  "Quick Meals",
  "Raw",
  "Salads",
  "Samosas",
  "Sandwiches",
  "Scotch Egg",
  "Shawarma",
  "Smoothies",
  "Soft Drinks",
  "Soy-Free",
  "Spaghetti",
  "Spicy",
  "Spicy Wings",
  "Spring Rolls",
  "Street Food",
  "Suya",
  "Sugar-Free",
  "Swallows",
  "Tea",
  "Toasted Bread",
  "Traditional Dishes",
  "Vegetable Soup",
  "Vegetarian",
  "Vegetarian Burger",
  "Vegetarian Pizza",
  "Vegetarian Salad",
  "Vegan",
  "Whole30",
  "Wine",
  "Wraps",
  "Yam Porridge",
  "Zobo",
];

export { addresses, background, foodTags };
